Trying to merge with git DIFF instead of PATCH.. see if it is less brittle.

diff --git a/gate-submodule-foodcritic b/gate-submodule-foodcritic
--- a/gate-submodule-foodcritic
+++ b/gate-submodule-foodcritic
@@ -13,13 +13,22 @@ if ! ( git clone ${GIT_CLONE_URL} ); then
     exit 1
 fi
 
-# Merge the proposed patch(es)
-cd ${GIT_REPO}
-if ! ( curl -s ${GIT_PATCH_URL} | git am ); then
+# -- TRYING ANOTHER METHOD -- #
+## Merge the proposed patch(es)
+#cd ${GIT_REPO}
+#if ! ( curl -s ${GIT_PATCH_URL} | git am ); then
+#    echo "Unable to merge proposed patch: ${GIT_PATCH_URL}"
+#    exit 1
+#fi
+#cd ../
+
+# Apply the proposed diff
+pushd ${GIT_REPO}
+if ! ( curl -s ${GIT_DIFF_URL} | git apply ); then
     echo "Unable to merge proposed patch: ${GIT_PATCH_URL}"
     exit 1
 fi
-cd ../
+popd
 
 # RVM is throwing an unbound variable error
 set +x
