add checkout to opencenter-install-scripts

diff --git a/gate-opencenter-install-scripts-syntax b/gate-opencenter-install-scripts-syntax
--- a/gate-opencenter-install-scripts-syntax
+++ b/gate-opencenter-install-scripts-syntax
@@ -16,6 +16,13 @@ if ! ( git clone ${GIT_SSH_URL} ); then
     exit 1
 fi
 
+pushd ${GIT_REPO}
+# Checkout the correct branch
+if ! ( git checkout ${GIT_BRANCH} ); then
+    echo "Unable to checkout Branch: ${GIT_BRANCH}"
+    exit 1
+fi
+
 # Apply the proposed diff
 pushd ${GIT_REPO}
 if ! ( curl -s -n ${GIT_DIFF_URL} | git apply ); then
