adding patches to test out building an Ubuntu-11.04 crowbar iso

diff --git a/jenkins-dell-crowbar-admin-iso b/jenkins-dell-crowbar-admin-iso
--- a/jenkins-dell-crowbar-admin-iso
+++ b/jenkins-dell-crowbar-admin-iso
@@ -67,10 +67,30 @@ fi
 ssh root@${IP} "cd /opt/crowbar && git checkout openstack-os-build"
 ssh root@${IP} "cd /opt/crowbar && git submodule init"
 ssh root@${IP} "cd /opt/crowbar && git submodule update"
-if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-10.10" ); then
+
+# Putting in patches to test out Crowbar on Ubuntu-11.04
+ssh root@${IP} "cd /opt/crowbar/barclamps/crowbar && git remote add upstream https://github.com/dellcloudedge/barclamp-crowbar.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/deployer && git remote add upstream https://github.com/dellcloudedge/barclamp-deployer.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/glance && git remote add upstream https://github.com/dellcloudedge/barclamp-glance.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/keystone && git remote add upstream https://github.com/dellcloudedge/barclamp-keystone.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/kong && git remote add upstream https://github.com/dellcloudedge/barclamp-kong.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/nova && git remote add upstream https://github.com/dellcloudedge/barclamp-nova.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/nova_dashboard && git remote add upstream https://github.com/dellcloudedge/barclamp-nova_dashboard.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/provisioner && git remote add upstream https://github.com/dellcloudedge/barclamp-provisioner.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/swift && git remote add upstream https://github.com/dellcloudedge/barclamp-swift.git && git pull upstream master"
+# ssh root@${IP} "cd /opt/crowbar/barclamps/ubuntu-install && git remote add upstream https://github.com/dellcloudedge/barclamp-ubuntu-install.git && git pull upstream master"
+ssh root@${IP} "cd /opt/crowbar/barclamps/ubuntu-install && git remote add upstream https://github.com/galstrom21/barclamp-ubuntu-install.git && git pull upstream master"
+
+if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-11.04" ); then
      echo "Error in tests"
      exit 1
 fi
+
+#if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-10.10" ); then
+#     echo "Error in tests"
+#     exit 1
+#fi
+
 scp root@${IP}:/opt/crowbar/crowbar-${iso_name}.iso .
 # scp crowbar-${iso_name}.iso openstack@${ISODEST}:~/incoming/crowbar.iso
 
