Commenting out more kong stuff until we re-factor it for ksl

diff --git a/jenkins-cs-precise b/jenkins-cs-precise
--- a/jenkins-cs-precise
+++ b/jenkins-cs-precise
@@ -80,10 +80,10 @@ sleep 20
 # Output package list before we run kong and exerstack
 ssh root@${IP} dpkg -l | grep '2012.1'
 
-if ! ( ssh root@${IP} "cd /opt/kong; ./run_tests.sh --nova" ); then
-    echo "Error in tests"
-    exit 1
-fi
+# if ! ( ssh root@${IP} "cd /opt/kong; ./run_tests.sh --nova" ); then
+    # echo "Error in tests"
+    # exit 1
+# fi
 
 if ! ( ssh root@${IP} "cd /opt/exerstack; ./exercise.sh" ); then
     echo "Error in tests"
