move knife commands local

diff --git a/jenkins-cs-multi-node b/jenkins-cs-multi-node
--- a/jenkins-cs-multi-node
+++ b/jenkins-cs-multi-node
@@ -19,6 +19,8 @@ function err_cleanup_chef() {
         exit 0
     fi
 
+    chef_env_deleted=0
+
     for host in ${host_info[@]}; do
         name=$(echo $host | cut -d':' -f1)
         role=$(echo $host | cut -d':' -f2)
@@ -28,9 +30,13 @@ function err_cleanup_chef() {
 
         echo "destroying $host"
         # Delete node and client from chef-server
-        ssh root@${ip} "knife node delete \$HOSTNAME -y -E ${chef_env} || :"
-        ssh root@${ip} "knife client delete \$HOSTNAME -y -E ${chef_env} || :"
-        ssh root@${ip} "/opt/opscode/bin/knife environment delete ${chef_env} -y || :"
+        knife node delete ${name} -y -E ${chef_env} || :
+        knife client delete ${name} -y -E ${chef_env} || :
+
+        if [ $chef_env_set -eq 0 ]; then
+            knife environment delete ${chef_env} -y || :
+            chef_env_deleted=1
+        fi
 
         sudo virsh destroy ${name}
         sleep 5
@@ -177,8 +183,8 @@ for host in ${host_info[@]}; do
     OLD_IFS=$IFS
     IFS=","
     for role_variant in ${role}; do
-        if ! ( ssh root@${ip} "/opt/opscode/bin/knife node run_list add \$HOSTNAME ${role_variant} -E ${chef_env}" ); then
-            echo "Error adding role to node"
+        if ! ( /opt/opscode/bin/knife node run_list add ${name} ${role_variant} -E ${chef_env} ); then
+            echo "Error adding role ${name} to node"
             err_cleanup_chef
             exit 1
         fi
@@ -219,15 +225,19 @@ fi
 
 trap - SIGINT SIGTERM EXIT ERR
 
+chef_env_deleted=0
 # Cleanup after the run
 for host in ${host_info[@]}; do
     name=$(echo $host | cut -d':' -f1)
     node=$(echo $host | cut -d':' -f2)
     ip=$(echo $host | cut -d':' -f3)
     # Delete node and client from chef-server
-    ssh root@${ip} "/opt/opscode/bin/knife node delete \$HOSTNAME -y -E ${chef_env} || :"
-    ssh root@${ip} "/opt/opscode/bin/knife client delete \$HOSTNAME -y -E ${chef_env} || :"
-    ssh root@${ip} "/opt/opscode/bin/knife environment delete ${chef_env} -y || :"
+    knife node delete ${name} -y -E ${chef_env} || :
+    knife client delete ${name} -y -E ${chef_env} || :
+    if [ $chef_env_set -eq 0 ]; then
+        knife environment delete ${chef_env} -y || :
+        chef_env_deleted=1
+    fi
 
     sudo virsh destroy ${name}
     sleep 5
