add kong to the two node test

diff --git a/jenkins-cs-two-node b/jenkins-cs-two-node
--- a/jenkins-cs-two-node
+++ b/jenkins-cs-two-node
@@ -203,10 +203,10 @@ for host in ${host_info[@]}; do
             exit 1
         fi
 
-        #if ! ( ssh root@${ip} 'cd /opt/kong; ./run_tests.sh --version essex-final' ); then
-        #    echo "Kong test suite failed"
-        #    exit 1
-        #fi
+        if ! ( ssh root@${ip} 'cd /opt/kong; ./run_tests.sh --version essex-final' ); then
+            echo "Kong test suite failed"
+            exit 1
+        fi
     fi
 done
 
