two node

diff --git a/jenkins-cs-two-node b/jenkins-cs-two-node
--- a/jenkins-cs-two-node
+++ b/jenkins-cs-two-node
@@ -152,10 +152,10 @@ for host in ${host_info[@]}; do
     ssh root@${ip} 'rm -rf /opt/exerstack/exercises/bundle.sh'
     # ssh root@${ip} 'rm -rf /opt/exerstack/exercises/keystone-manage.sh'
 
-    #if ! ( ssh root@${ip} 'cd /opt/exerstack; ./exercise.sh' ); then
-    #    echo "Exerstack test suite failed"
-    #    exit 1
-    #fi
+    if ! ( ssh root@${ip} 'cd /opt/exerstack; ./exercise.sh' ); then
+        echo "Exerstack test suite failed"
+        exit 1
+    fi
 
     #if ! ( ssh root@${ip} 'cd /opt/kong; ./run_tests.sh --version essex-final' ); then
     #    echo "Kong test suite failed"
