add exerstack back in

diff --git a/jenkins-cs-precise b/jenkins-cs-precise
--- a/jenkins-cs-precise
+++ b/jenkins-cs-precise
@@ -87,7 +87,7 @@ ssh root@${IP} 'mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; /opt/opscod
 
 ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME role[jenkins-allinone]'
 # ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[kong]'
-#ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[exerstack]'
+ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[exerstack]'
 ssh root@${IP} '/opt/opscode/bin/chef-client'
 
 sleep 20s
@@ -98,10 +98,10 @@ ssh root@${IP} 'rm -rf /opt/exerstack/exercises/euca.sh'
 ssh root@${IP} 'rm -rf /opt/exerstack/exercises/glance.sh'
 ssh root@${IP} 'rm -rf /opt/exerstack/exercises/keystone-manage.sh'
 
-#if ! ( ssh root@${IP} 'cd /opt/exerstack; ./exercise.sh' ); then
-#    echo "Exerstack test suite failed"
-#    exit 1
-#fi
+if ! ( ssh root@${IP} 'cd /opt/exerstack; ./exercise.sh' ); then
+    echo "Exerstack test suite failed"
+    exit 1
+fi
 
 trap - SIGINT SIGTERM EXIT ERR
 
