Fixing a typo, and trying to quiet the fullstack installer

diff --git a/jenkins-cs-precise b/jenkins-cs-precise
--- a/jenkins-cs-precise
+++ b/jenkins-cs-precise
@@ -72,8 +72,14 @@ else
   ssh root@${IP} "yum install -y wget tar"
 fi
 
+# Try to quiet installer
+ssh root@${IP} 'echo "alias wget=\"wget -q\"" >> ~/.bashrc '
+
 # Install ruby/chef via opscode's fullstack installer
-ssh root@${IP} "bash < <(curl -s http://s3.amazonaws.com/opscode-full-stack/install.sh)"
+if ! ( ssh root@${IP} "bash < <(curl -s http://s3.amazonaws.com/opscode-full-stack/install.sh)" ); then
+    echo "Unable to install Opscode FullStack Installer"
+    exit 1
+fi
 
 # Setup Hosted Chef
 ssh root@${IP} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; /opt/opscode/bin/knife configure client ./client-config'
@@ -87,10 +93,10 @@ ssh root@${IP} '/opt/opscode/bin/chef-client'
 sleep 20s
 
 # These tests are not working on essex yet
-ssh root@${IP} 'rm -rf /opt/exerstack/exercises/bundle.sh"
-ssh root@${IP} 'rm -rf /opt/exerstack/exercises/euca.sh"
-ssh root@${IP} 'rm -rf /opt/exerstack/exercises/glance.sh"
-ssh root@${IP} 'rm -rf /opt/exerstack/exercises/keystone-manage.sh"
+ssh root@${IP} 'rm -rf /opt/exerstack/exercises/bundle.sh'
+ssh root@${IP} 'rm -rf /opt/exerstack/exercises/euca.sh'
+ssh root@${IP} 'rm -rf /opt/exerstack/exercises/glance.sh'
+ssh root@${IP} 'rm -rf /opt/exerstack/exercises/keystone-manage.sh'
 
 if ! ( ssh root@{$IP} 'cd /opt/exerstack; ./exercise.sh' ); then
     echo "Exerstack test suite failed"
