Apparently sudo -E will preserve env variables

diff --git a/jenkins-dell-crowbar-admin-node b/jenkins-dell-crowbar-admin-node
--- a/jenkins-dell-crowbar-admin-node
+++ b/jenkins-dell-crowbar-admin-node
@@ -51,24 +51,24 @@ function ipmi_poweron() {
     ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${ip} -U ${DRACUSER} -P ${DRACPASS} chassis power on"
 }
 
-#function crowbar_proposal() {
-#    # $1 - Service Name
-#    # $2 - Proposal Name
-#    # $3 - Action (create|commit)
-#    service=$1
-#    proposal_name=$2
-#    action=$3
-#    cmd='/opt/dell/bin/crowbar'
-#    log "Executing crowbar_proposal using:"
-#    log " Service: ${service}"
-#    log " Proposal Name: ${proposal_name}"
-#    log " Action: ${action}"
-#
-#    if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i ${cmd}_${service} proposal ${action} ${proposal_name}' ); then
-#        log "Unable to ${action} the ${service} Proposal"
-#        exit 1
-#    fi
-#}
+function crowbar_proposal() {
+    # $1 - Service Name
+    # $2 - Proposal Name
+    # $3 - Action (create|commit)
+    service=$1
+    proposal_name=$2
+    action=$3
+    cmd='/opt/dell/bin/crowbar'
+    log "Executing crowbar_proposal using:"
+    log " Service: ${service}"
+    log " Proposal Name: ${proposal_name}"
+    log " Action: ${action}"
+
+    if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -E -i ${cmd}_${service} proposal ${action} ${proposal_name}' ); then
+        log "Unable to ${action} the ${service} Proposal"
+        exit 1
+    fi
+}
 
 # Hide ipmi info
 source ~jenkins/.ipmirc
@@ -147,21 +147,21 @@ fi
 
 ##################################################
 # Push MYSQL Proposal
-#crowbar_proposal "mysql" "jenkins" "create"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal create jenkins' ); then
-    echo "Unable to create the MySQL Proposal"
-    exit 1
-fi
+crowbar_proposal "mysql" "jenkins" "create"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal create jenkins' ); then
+#    echo "Unable to create the MySQL Proposal"
+#    exit 1
+#fi
 
 ## Ghetto Hack since we are disabling IPMI Barclamp
 ## SET PXE BOOT on CONTROLLER NODE 
 ipmi_set_pxe ${CONTROLLERIP}
 
-#crowbar_proposal "mysql" "jenkins" "commit"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal commit jenkins' ); then
-    echo "Unable to commit the MySQL Proposal"
-    exit 1
-fi
+crowbar_proposal "mysql" "jenkins" "commit"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal commit jenkins' ); then
+#    echo "Unable to commit the MySQL Proposal"
+#    exit 1
+#fi
 
 # Loop and wait for the MySQL Proposal to get applied
 count=1
@@ -182,16 +182,16 @@ done
 
 ##################################################
 # Push the Keystone Proposal
-#crowbar_proposal "keystone" "jenkins" "create"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal create jenkins' ); then
-    echo "Unable to create the Keystone Proposal"
-    exit 1
-fi
-#crowbar_proposal "keystone" "jenkins" "commit"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal commit jenkins' ); then
-    echo "Unable to commit the Keystone Proposal"
-    exit 1
-fi
+crowbar_proposal "keystone" "jenkins" "create"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal create jenkins' ); then
+#    echo "Unable to create the Keystone Proposal"
+#    exit 1
+#fi
+crowbar_proposal "keystone" "jenkins" "commit"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal commit jenkins' ); then
+#    echo "Unable to commit the Keystone Proposal"
+#    exit 1
+#fi
 # Loop and wait for the Keystone Proposal to get applied
 count=1
 while [ $count -lt 15 ]; do
@@ -210,16 +210,16 @@ done
 
 ##################################################
 # Push the Glance Proposal
-#crowbar_proposal "glance" "jenkins" "create"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal create jenkins' ); then
-    echo "Unable to create the Glance Proposal"
-    exit 1
-fi
-#crowbar_proposal "glance" "jenkins" "commit"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal commit jenkins' ); then
-    echo "Unable to commit the Glance Proposal"
-    exit 1
-fi
+crowbar_proposal "glance" "jenkins" "create"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal create jenkins' ); then
+#    echo "Unable to create the Glance Proposal"
+#    exit 1
+#fi
+crowbar_proposal "glance" "jenkins" "commit"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal commit jenkins' ); then
+#    echo "Unable to commit the Glance Proposal"
+#    exit 1
+#fi
 # Loop and wait for the Keystone Proposal to get applied
 count=1
 while [ $count -lt 15 ]; do
@@ -238,16 +238,16 @@ done
 
 ##################################################
 # Push the Nova Proposal
-#crowbar_proposal "nova" "jenkins" "create"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal create jenkins' ); then
-    echo "Unable to create the Nova Proposal"
-    exit 1
-fi
-#crowbar_proposal "nova" "jenkins" "commit"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal commit jenkins' ); then
-    echo "Unable to commit the Nova Proposal"
-    exit 1
-fi
+crowbar_proposal "nova" "jenkins" "create"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal create jenkins' ); then
+#    echo "Unable to create the Nova Proposal"
+#    exit 1
+#fi
+crowbar_proposal "nova" "jenkins" "commit"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal commit jenkins' ); then
+#    echo "Unable to commit the Nova Proposal"
+#    exit 1
+#fi
 if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova list | grep jenkins' ); then
     echo "Nova proposal not applied"
     exit 1
@@ -256,16 +256,16 @@ fi
 
 ##################################################
 # Push the Dash Proposal
-#crowbar_proposal "nova_dashboard" "jenkins" "create"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal create jenkins' ); then
-    echo "Unable to create the Dash Proposal"
-    exit 1
-fi
-#crowbar_proposal "nova_dashboard" "jenkins" "commit"
-if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal commit jenkins' ); then
-    echo "Unable to commit the Dash Proposal"
-    exit 1
-fi
+crowbar_proposal "nova_dashboard" "jenkins" "create"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal create jenkins' ); then
+#    echo "Unable to create the Dash Proposal"
+#    exit 1
+#fi
+crowbar_proposal "nova_dashboard" "jenkins" "commit"
+#if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal commit jenkins' ); then
+#    echo "Unable to commit the Dash Proposal"
+#    exit 1
+#fi
 if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard list | grep jenkins' ); then
     echo "Dash proposal not applied"
     exit 1
