switching from natty to maverick

diff --git a/jenkins-dell-crowbar-admin-iso b/jenkins-dell-crowbar-admin-iso
--- a/jenkins-dell-crowbar-admin-iso
+++ b/jenkins-dell-crowbar-admin-iso
@@ -69,15 +69,15 @@ ssh root@${IP} "cd /opt/crowbar && git checkout openstack-os-build"
 ssh root@${IP} "cd /opt/crowbar && git submodule init"
 ssh root@${IP} "cd /opt/crowbar && git submodule update"
 
-if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-11.04" ); then
-     echo "Error in tests"
-     exit 1
-fi
-
-#if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-10.10" ); then
+#if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-11.04" ); then
 #     echo "Error in tests"
 #     exit 1
 #fi
+
+if ! ( ssh root@${IP} "cd /opt/crowbar && DEBIAN_FRONTEND=noninteractive VERSION='${iso_name}' ./build_crowbar.sh ubuntu-10.10" ); then
+     echo "Error in tests"
+     exit 1
+fi
 
 scp root@${IP}:/opt/crowbar/crowbar-${iso_name}.iso .
 # scp crowbar-${iso_name}.iso openstack@${ISODEST}:~/incoming/crowbar.iso
