trying to use a template environment file

diff --git a/jenkins-cs-precise b/jenkins-cs-precise
--- a/jenkins-cs-precise
+++ b/jenkins-cs-precise
@@ -32,7 +32,7 @@ function err_cleanup_chef() {
     scp root@${IP}:/var/chef/cache/chef-stacktrace.out chef-stacktrace.out.log || :
 
     echo "capturing collectd output"
-    scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r root@${IP}:/etc/collectd root@50.57.52.245:~/ || :
+    scp -r root@${IP}:/etc/collectd/ . || :
 
 
     # Delete node and client from chef-server
@@ -102,6 +102,17 @@ if ! ( ssh root@${IP} "bash < <(curl -s http://s3.amazonaws.com/opscode-full-sta
 fi
 
 EDITOR=/bin/true knife environment create ${kvm_instance_name}
+
+# lets create the chef environment
+tmp_env=$(mktemp)
+cat ~/jenkins-build/files/example-environment.json | sed -e "s/REPLACEWITHNAME/${kvm_instance_name}/" > ${tmp_env}.json
+if ! ( knife environment from file ${tmp_env}.json ); then
+    echo "Unable to create environment from ${tmp_env}.json"
+    exit 1
+else
+    rm ${tmp_env}.json
+    knife environment show ${chef_env} -Fj
+fi
 
 # Setup Hosted Chef
 #ssh root@${IP} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; knife configure client ./client-config'
