adding a if block around registering with chef-server because the fedora image is not cleaning itself up properlly all the time

diff --git a/jenkins-cs-precise b/jenkins-cs-precise
--- a/jenkins-cs-precise
+++ b/jenkins-cs-precise
@@ -35,10 +35,7 @@ function err_cleanup_chef() {
 }
 
 MEMORY=2048000
-if ! maybe_make_kvm_instance $kvm_instance_name; then
-    echo "Unable to create KVM Instance"
-    exit 1
-fi
+maybe_make_kvm_instance $kvm_instance_name
 trap "err_cleanup_chef ${kvm_instance_name}" SIGINT SIGTERM EXIT ERR
 start_kvm_instance $kvm_instance_name ${IP} http://archive.ubuntu.com/ubuntu precise main
 
@@ -86,7 +83,10 @@ fi
 
 # Setup Hosted Chef
 ssh root@${IP} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; /opt/opscode/bin/knife configure client ./client-config'
-ssh root@${IP} 'mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; /opt/opscode/bin/chef-client'
+if ! ( ssh root@${IP} 'mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; /opt/opscode/bin/chef-client' ); then
+    echo "Unable to register with chef-server"
+    exit 1
+fi
 
 ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME role[jenkins-allinone]'
 # ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[kong]'
