add exerstack and kong tests back in

diff --git a/jenkins-cs-multi-node b/jenkins-cs-multi-node
--- a/jenkins-cs-multi-node
+++ b/jenkins-cs-multi-node
@@ -209,21 +209,21 @@ echo "running tests against the controller node"
 
 echo "setting up the routes"
 
-#get_ip_by_role "api"
-#controller_ip=$T_IP
-#get_ip_by_role "compute" 
-#compute_ip=$T_IP
-#ssh root@${controller_ip} "ip route add 192.168.100.0/24 via ${compute_ip}"
+get_ip_by_role "api"
+controller_ip=$T_IP
+get_ip_by_role "compute" 
+compute_ip=$T_IP
+ssh root@${controller_ip} "ip route add 192.168.100.0/24 via ${compute_ip}"
 
-#ssh root@${controller_ip} 'rm -rf /opt/exerstack/exercises/bundle.sh'
-#if ! ( ssh root@${controller_ip} 'cd /opt/exerstack; ./exercise.sh' ); then
-#    echo "Exerstack test suite failed"
-#    exit 1
-#fi
-#if ! ( ssh root@${controller_ip} 'cd /opt/kong; ./run_tests.sh --version essex-final' ); then
-#    echo "Kong test suite failed"
-#    exit 1
-#fi
+ssh root@${controller_ip} 'rm -rf /opt/exerstack/exercises/bundle.sh'
+if ! ( ssh root@${controller_ip} 'cd /opt/exerstack; ./exercise.sh' ); then
+    echo "Exerstack test suite failed"
+    exit 1
+fi
+if ! ( ssh root@${controller_ip} 'cd /opt/kong; ./run_tests.sh --version essex-final' ); then
+    echo "Kong test suite failed"
+    exit 1
+fi
 
 trap - SIGINT SIGTERM EXIT ERR
 
