trying to sort out runlist ordering.. and adding back in kong and exerstack.

diff --git a/jenkins-cs-swift-three-node b/jenkins-cs-swift-three-node
--- a/jenkins-cs-swift-three-node
+++ b/jenkins-cs-swift-three-node
@@ -76,7 +76,7 @@ function get_ip_by_role() {
 # the naming of these is extremely important - they must match the chef roles
 declare -a nodes
 if [ ${AUTHTYPE} == "keystone" ]; then
-    nodes=( node1:role[base],role[jenkins-mysql-master],role[keystone],recipe[kong],recipe[exerstack],role[swift-management-server],role[swift-proxy-server],role[swift-object-server],role[swift-container-server],role[swift-account-server]
+    nodes=( node1:role[base],role[jenkins-mysql-master],role[keystone],role[swift-management-server],role[swift-proxy-server],role[swift-object-server],role[swift-container-server],role[swift-account-server],recipe[kong],recipe[exerstack]
             node2:role[base],role[swift-object-server],role[swift-container-server],role[swift-account-server]
             node3:role[base],role[swift-object-server],role[swift-container-server],role[swift-account-server]
           )
@@ -236,23 +236,31 @@ done
 
 sleep 20s
 
-echo "running tests against the controller node"
+# Swift needs a bunch of runs
+for x in $(seq 1 2); do
+    for host in ${!host_info[@]}; do
+        name=$(echo ${host_info[$host]} | cut -d':' -f1)
+        role=$(echo ${host_info[$host]} | cut -d':' -f2)
+        ip=$(echo ${host_info[$host]} | cut -d':' -f3)
+        ssh root@${ip} "/opt/opscode/bin/chef-client -E ${chef_env}"
+    done
+done
 
+echo "running tests against the swift-management node"
 get_ip_by_role "kong"
 kong_ip=$T_IP
 
 # uncomment this once swift is deployable
-#ssh root@${kong_ip} 'rm -rf /opt/exerstack/exercises/bundle.sh'
-#if ! ( ssh root@${kong_ip} 'cd /opt/exerstack; ./exercise.sh' ); then
-#    echo "Exerstack test suite failed"
-#    err_cleanup_chef
-#    exit 1
-#fi
-#if ! ( ssh root@${kong_ip} 'cd /opt/kong; ./run_tests.sh --version essex-final --swift' ); then
-#    echo "Kong test suite failed"
-#    err_cleanup_chef
-#    exit 1
-#fi
+if ! ( ssh root@${kong_ip} 'cd /opt/exerstack; ./exercise.sh essex-final keystone.sh swift.sh' ); then
+    echo "Exerstack test suite failed"
+    err_cleanup_chef
+    exit 1
+fi
+if ! ( ssh root@${kong_ip} 'cd /opt/kong; ./run_tests.sh --version essex-final --swift' ); then
+    echo "Kong test suite failed"
+    err_cleanup_chef
+    exit 1
+fi
 
 trap - SIGINT SIGTERM EXIT ERR
 
