knife expects the from file filename to end with .json or .js

diff --git a/jenkins-cs-swift-three-node b/jenkins-cs-swift-three-node
--- a/jenkins-cs-swift-three-node
+++ b/jenkins-cs-swift-three-node
@@ -96,12 +96,12 @@ chef_env_set=0
 
 # lets create the chef environment
 tmp_env=$(mktemp)
-cat ~/jenkins-build/files/${AUTHTYPE}-swift-environment.json | sed -e "s/REPLACEME/${chef_env}/" > ${tmp_env}
-if ! ( knife environment from file ${tmp_env} ); then
-    echo "Unable to create environment from ${tmp_env}"
+cat ~/jenkins-build/files/${AUTHTYPE}-swift-environment.json | sed -e "s/REPLACEME/${chef_env}/" > ${tmp_env}.json
+if ! ( knife environment from file ${tmp_env}.json ); then
+    echo "Unable to create environment from ${tmp_env}.json"
     exit 1
 else
-    rm ${tmp_env}
+    rm ${tmp_env}.json
     chef_env_set=1
 fi
 
