moving env creation to use a templated file

diff --git a/jenkins-cs-two-node b/jenkins-cs-two-node
--- a/jenkins-cs-two-node
+++ b/jenkins-cs-two-node
@@ -30,7 +30,7 @@ function err_cleanup_chef() {
         # Delete node and client from chef-server
         knife node delete ${name} -y ||
         knife client delete ${name} -y || :
-        /opt/opscode/bin/knife environment delete ${chef_env} -y || :
+        knife environment delete ${chef_env} -y || :
 
         sudo virsh destroy ${name}
         sleep 5
@@ -153,19 +153,28 @@ for host in ${host_info[@]}; do
     fi
 
     # Setup Hosted Chef
-    #ssh root@${ip} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; /opt/opscode/bin/knife configure client ./client-config'
+    #ssh root@${ip} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; knife configure client ./client-config'
  
     # Setup chef to use our jenkins server
-    ssh root@${ip} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef-server.tgz; tar -xvzf chef-server.tgz; /opt/opscode/bin/knife configure client ./client-config'
+    ssh root@${ip} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef-server.tgz; tar -xvzf chef-server.tgz; knife configure client ./client-config'
 
     ssh root@${ip} "echo 'environment \"${chef_env}\"' >> ~/client-config/client.rb"
 
+    # lets create the chef environment
     if [ $chef_env_set -eq 0 ]; then
-        EDITOR=/bin/true knife environment create ${chef_env} -d ${chef_env}
-        chef_env_set=1
+        tmp_env=$(mktemp)
+        cat ~/jenkins-build/files/example-environment.json | sed -e "s/REPLACEWITHNAME/${chef_env}/" > ${tmp_env}.json
+        if ! ( knife environment from file ${tmp_env}.json ); then
+            echo "Unable to create environment from ${tmp_env}.json"
+            exit 1
+        else
+            chef_env_set=1
+            rm ${tmp_env}.json
+            knife environment show ${chef_env} -Fj
+        fi
     fi
 
-    if ! ( ssh root@${ip} "mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; /opt/opscode/bin/chef-client " ); then
+    if ! ( ssh root@${ip} "mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; chef-client " ); then
         echo "Unable to register with chef-server"
         err_cleanup_chef
         exit 1
@@ -173,15 +182,15 @@ for host in ${host_info[@]}; do
 
     case "$role" in
         "controller")
-            /opt/opscode/bin/knife node run_list add ${name} role[jenkins-controller]
-            /opt/opscode/bin/knife node run_list add ${name} recipe[kong]
-            /opt/opscode/bin/knife node run_list add ${name} recipe[exerstack]
+            knife node run_list add ${name} role[jenkins-controller]
+            knife node run_list add ${name} recipe[kong]
+            knife node run_list add ${name} recipe[exerstack]
             ;;
         "compute")
-            /opt/opscode/bin/knife node run_list add ${name} role[jenkins-compute]
+            knife node run_list add ${name} role[jenkins-compute]
             ;;
     esac
-    ssh root@${ip} "/opt/opscode/bin/chef-client "
+    ssh root@${ip} "chef-client "
 
 done
 
@@ -237,9 +246,9 @@ for host in ${host_info[@]}; do
     node=$(echo $host | cut -d':' -f2)
     ip=$(echo $host | cut -d':' -f3)
     # Delete node and client from chef-server
-    /opt/opscode/bin/knife node delete ${name} -y || :
-    /opt/opscode/bin/knife client delete ${name} -y || :
-    /opt/opscode/bin/knife environment delete ${chef_env} -y || :
+    knife node delete ${name} -y || :
+    knife client delete ${name} -y || :
+    knife environment delete ${chef_env} -y || :
 
     sudo virsh destroy ${name}
     sleep 5
