Add exerstack

diff --git a/jenkins-deb-chefsolo b/jenkins-deb-chefsolo
--- a/jenkins-deb-chefsolo
+++ b/jenkins-deb-chefsolo
@@ -77,7 +77,7 @@ cat > /tmp/${kvm_instance_name}.json <<EOF
   "package_component": "${NOVA_RELEASE}-${MILESTONE}",
   "virt_type": "qemu",
 
-  "run_list": [ "recipe[apt]", "recipe[openstack::allinone]", "recipe[kong]" ]
+  "run_list": [ "recipe[apt]", "recipe[openstack::allinone]", "recipe[kong]", "recipe[exerstack]" ]
 }
 EOF
 
@@ -92,6 +92,11 @@ sleep 20
 # box should be configured now....
 
 if ! ( ssh root@${IP} "cd /opt/kong; ./run_tests.sh --nova" ); then
+    echo "Error in tests"
+    exit 1
+fi
+
+if ! ( ssh root@${IP} "cd /opt/exerstack; ./exercise.sh" ); then
     echo "Error in tests"
     exit 1
 fi
